import { Montserrat,Heebo } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Footer from "./common/Footer";
import { ToastContainer } from "react-toastify";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Mainlayout from "./Mainlayout";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
});

const heebo = Heebo({
  variable: "--font-heebo",
  subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${heebo.variable}`}>
      <body>
        <Mainlayout>
           <Header/>
        {children}
        <Footer/>
        <ToastContainer/>
        </Mainlayout>
      </body>
   
    </html>
  );
}
